In [1]:
import numpy as np

array = np.array([1,2,3])

print(array.size)    # 배열의 크기
print(array.dtype)   # 배열 원소의 타입
print(array[2])      # 인덱스 2의 원소

3
int32
3


In [3]:
import numpy as np

array1 = np.arange(4)          
array2 = np.zeros((4,4),dtype = float)
array3 = np.ones((3,3),dtype = str)
# 0부터 9까지 랜덤하게 초기화 된 배열 만들기
array4 = np.random.randint(0,10,(3,3))
# 평균이 0이고 표준편차가 1인 표준 정규를 띄는 배열
array5 = np.random.normal(0,1,(3,3))    


print(array1)
print(array2)
print(array3)
print(array4)
print(array5)

[0 1 2 3]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[['1' '1' '1']
 ['1' '1' '1']
 ['1' '1' '1']]
[[5 2 3]
 [6 3 1]
 [0 9 7]]
[[-2.98068357 -0.02297912 -1.18773962]
 [-1.23957023  0.30943528 -1.44324565]
 [ 1.95792435 -1.61706642  0.81912961]]


배열 합치기

In [4]:
import numpy as np

array1 = np.array([1,2,3])
array2 = np.array([4,5,6])
array3 = np.concatenate([array1, array2])

print(array3.shape)
print(array3)

(6,)
[1 2 3 4 5 6]


배열 형태 바꾸기

In [7]:

import numpy as np

array1 = np.array([1,2,3,4])
array2 = array1.reshape((2,2))

print(array2.shape)
print(array2)

(2, 2)
[[1 2]
 [3 4]]


배열 세로 축으로 합치기

In [22]:
import numpy as np

array1 = np.arange(4).reshape(1,4)
array2 = np.arange(8).reshape(2,4)

array3 = np.concatenate([array1,array2],axis = 0)
print(array3.shape)
print(array3)

(3, 4)
[[0 1 2 3]
 [0 1 2 3]
 [4 5 6 7]]


배열 나누기

In [15]:
import numpy as np

array = np.arange(8).reshape(2,4)
 # array를 [2] 기준으로 axis = 1 -> 열을 기준으로 나누기
left, right = np.split(array,[2],axis=1)  
print(left.shape)
print(left)
print(right.shape)
print(right)
#print(right[1][1])

(2, 2)
[[0 1]
 [4 5]]
(2, 2)
[[2 3]
 [6 7]]


In [20]:
import numpy as np

array = np.arange(12).reshape(3,4)
left, right = np.split(array,[2],axis=0)
print(left)

[[0 1 2 3]
 [4 5 6 7]]


In [28]:
import numpy as np

array= np.random.randint(1,10,size = 4).reshape(2,2)
result_array = array*10
print(result_array)

[[80 90]
 [30 20]]


In [39]:
import numpy as np

array1 = np.arange(4).reshape(2,2)
array2 = np.arange(2)
array3 = array1 + array2
array4 = np.arange(2).reshape(2,1)
array5 = array1 + array4

print(array1)
print(array2)
print(array3)
print(array4)
print(array5)

[[0 1]
 [2 3]]
[0 1]
[[0 2]
 [2 4]]
[[0]
 [1]]
[[0 1]
 [3 4]]


In [32]:
import numpy as np

array1 = np.arange(0,8).reshape(2,4)
array2 = np.arange(0,8).reshape(2,4)
array3 = np.concatenate([array1, array2],axis=0)
array4 = np.arange(0,4).reshape(4,1)

print(array3)
print(array4)
print(array3 + array4)

[[0 1 2 3]
 [4 5 6 7]
 [0 1 2 3]
 [4 5 6 7]]
[[0]
 [1]
 [2]
 [3]]
[[ 0  1  2  3]
 [ 5  6  7  8]
 [ 2  3  4  5]
 [ 7  8  9 10]]


In [34]:
import numpy as np

array1 = np.arange(16).reshape(4,4)
print(array1)

array2 = array1 <10
print(array2)

array1[array2] = 100          # True 값이 array2의 원소로 바뀜
print(array1)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True False False]
 [False False False False]]
[[100 100 100 100]
 [100 100 100 100]
 [100 100  10  11]
 [ 12  13  14  15]]


In [35]:
import numpy as np

array = np.arange(16).reshape(4,4)

print("최댓값: ",np.max(array))
print("최솟값: ",np.min(array))
print("합계: ",np.sum(array))
print("평균값: ",np.mean(array))

최댓값:  15
최솟값:  0
합계:  120
평균값:  7.5


In [38]:
import numpy as np

array = np.arange(16).reshape(4,4)

print(array)
print("합계: ",np.sum(array,axis=0))
print("합계: ",np.sum(array, axis=1))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
합계:  [24 28 32 36]
합계:  [ 6 22 38 54]
